from __future__ import annotations

import re
from pathlib import Path
from typing import AsyncGenerator

import litellm

from services.agent.src.agent.base import BaseAgent
from services.agent.src.agent.critics.citation_checker import check_citations, strip_uncited_claims
from services.agent.src.agent.critics.style_critic import run_style_critic
from services.agent.src.agent.skills.match_student_style import MatchStudentStyleSkill
from services.agent.src.agent.skills.retrieve_corpus import RetrieveCorpusSkill
from shared.src.shared.config import load_model_config
from shared.src.shared.models import MessageRole, Mode, Session

_PROMPT_ROOT = Path("prompts/aw_agent")

ESSAY_DISCLAIMER = (
    "\n\n---\n"
    "_This sample essay was generated by an AI tutor for study purposes only. "
    "Do not submit it as your own work._"
)

_ARGUMENT_KEYWORDS = re.compile(
    r"\b(the following|the argument|critique|examine the|stated and/or unstated|"
    r"write a response in which you examine|evaluate the argument)\b",
    re.IGNORECASE,
)

_MIN_PERSONAL_ESSAYS = 2


def _load_prompt(mode: Mode) -> str:
    path = _PROMPT_ROOT / mode.value / "v1.md"
    raw = path.read_text()
    return re.sub(r"^---\n.*?\n---\n", "", raw, flags=re.DOTALL).strip()


def _format_chunks_for_context(chunks: list) -> str:
    if not chunks:
        return ""
    lines = ["\n\n## Reference Material\n"]
    for i, chunk in enumerate(chunks, start=1):
        text = chunk.get("text", "") if isinstance(chunk, dict) else getattr(chunk, "text", "")
        tier = chunk.get("tier", "global") if isinstance(chunk, dict) else getattr(chunk, "tier", "global")
        section = chunk.get("page_or_section", "") if isinstance(chunk, dict) else getattr(chunk, "page_or_section", "")
        tier_label = {"global": "Official ETS material", "school": "Course notes", "candidate": "Your notes"}.get(tier, "Reference")
        lines.append(f"[{i}] ({tier_label} — {section})\n{text}")
    return "\n\n".join(lines)


def _format_exemplars(exemplars: list[str]) -> str:
    if not exemplars:
        return ""
    lines = ["\n\n## Your Previous Writing (style reference)\n"]
    for i, essay in enumerate(exemplars, start=1):
        lines.append(f"Example {i}:\n{essay}")
    return "\n\n".join(lines)


def _build_messages(
    session: Session, user_message: str, system_prompt: str,
    chunk_context: str, exemplar_context: str = ""
) -> list[dict]:
    messages: list[dict] = [{"role": "system", "content": system_prompt}]
    for msg in session.history:
        role = "user" if msg.role == MessageRole.candidate else "assistant"
        messages.append({"role": role, "content": msg.content})
    content = user_message
    if exemplar_context:
        content = f"{content}\n{exemplar_context}"
    if chunk_context:
        content = f"{content}\n{chunk_context}"
    messages.append({"role": "user", "content": content})
    return messages


async def _collect_stream(stream) -> tuple[list[str], str]:
    tokens: list[str] = []
    async for chunk in stream:
        content = chunk.choices[0].delta.content
        if content:
            tokens.append(content)
    return tokens, "".join(tokens)


class AWAgent(BaseAgent):
    """
    GRE Analytical Writing agent.

    Tutor mode: plan only (outline + thesis + evidence pointers).
    Solve mode: complete essay with:
      - retrieve-corpus → inject as numbered [N] references
      - personal style exemplars (if opted-in and >= 2 essays available)
      - style critic (Haiku-tier) → one rewrite pass on structural violation
      - citation checker → strip invalid citations on persistent failure
      - non-removable disclaimer appended
    """

    def __init__(
        self,
        model_config_path: str | None = None,
        retrieve_corpus_skill: RetrieveCorpusSkill | None = None,
        match_style_skill: MatchStudentStyleSkill | None = None,
    ) -> None:
        self._model_config = load_model_config(model_config_path)
        self._retrieve_skill = retrieve_corpus_skill or RetrieveCorpusSkill()
        self._match_style_skill = match_style_skill or MatchStudentStyleSkill()
        self._model_config_path = model_config_path

    async def run(self, session: Session, message: str) -> AsyncGenerator[str | dict, None]:
        chunks = await self._retrieve(session, message)
        chunk_context = _format_chunks_for_context(chunks)

        if session.mode == Mode.tutor:
            async for item in self._tutor_turn(session, message, chunk_context, chunks):
                yield item
        else:
            async for item in self._solve_turn(session, message, chunk_context, chunks):
                yield item

    # ── tutor mode ────────────────────────────────────────────────────────────

    async def _tutor_turn(
        self, session: Session, message: str, chunk_context: str, chunks: list
    ) -> AsyncGenerator[str | dict, None]:
        system_prompt = _load_prompt(Mode.tutor)
        messages = _build_messages(session, message, system_prompt, chunk_context)
        model = self._model_config.litellm_model("aw_agent")
        temperature = self._model_config.role("aw_agent").temperature

        # Attempt 1
        response = await litellm.acompletion(model=model, messages=messages, temperature=temperature, stream=True)
        tokens, full_text = await _collect_stream(response)
        valid, invalid = self._check_citations(full_text, len(chunks))

        if valid:
            for token in tokens:
                yield token
            yield {"citation_stripped": False}
            return

        # Retry on citation failure
        retry_messages = messages + [{"role": "assistant", "content": f"[Invalid citations: {', '.join(invalid)}. Must only cite [1]–[{len(chunks)}].]"}]
        response = await litellm.acompletion(model=model, messages=retry_messages, temperature=temperature, stream=True)
        tokens, full_text = await _collect_stream(response)
        valid, invalid = self._check_citations(full_text, len(chunks))

        if valid:
            for token in tokens:
                yield token
            yield {"citation_stripped": False}
            return

        yield strip_uncited_claims(full_text, invalid)
        yield {"citation_stripped": True}

    # ── solve mode ────────────────────────────────────────────────────────────

    async def _solve_turn(
        self, session: Session, message: str, chunk_context: str, chunks: list
    ) -> AsyncGenerator[str | dict, None]:
        system_prompt = _load_prompt(Mode.solve)
        model = self._model_config.litellm_model("aw_agent")
        temperature = self._model_config.role("aw_agent").temperature

        # Personal style exemplars (if opted-in + >= 2 essays)
        exemplars = await self._get_personal_style_exemplars(session)
        exemplar_context = _format_exemplars(exemplars) if len(exemplars) >= _MIN_PERSONAL_ESSAYS else ""

        messages = _build_messages(session, message, system_prompt, chunk_context, exemplar_context)

        # Generate essay
        response = await litellm.acompletion(model=model, messages=messages, temperature=temperature, stream=True)
        tokens, full_text = await _collect_stream(response)

        # Style critic — one rewrite pass on structural violation
        style_ok, style_feedback = await self._run_style_critic(full_text)
        if not style_ok:
            rewrite_messages = messages + [
                {"role": "assistant", "content": full_text},
                {"role": "user", "content": f"Please rewrite to fix: {style_feedback}. Keep the same thesis and evidence."},
            ]
            response = await litellm.acompletion(model=model, messages=rewrite_messages, temperature=temperature, stream=True)
            tokens, full_text = await _collect_stream(response)

        # Citation check
        valid, invalid = self._check_citations(full_text, len(chunks))
        if not valid:
            retry_messages = messages + [{"role": "assistant", "content": f"[Invalid citations: {', '.join(invalid)}. Must only cite [1]–[{len(chunks)}].]"}]
            response = await litellm.acompletion(model=model, messages=retry_messages, temperature=temperature, stream=True)
            tokens, full_text = await _collect_stream(response)
            valid, invalid = self._check_citations(full_text, len(chunks))
            if not valid:
                full_text = strip_uncited_claims(full_text, invalid)
                for token in tokens:
                    yield token
                yield ESSAY_DISCLAIMER
                yield {"citation_stripped": True}
                return

        # Emit essay + disclaimer
        for token in tokens:
            yield token
        yield ESSAY_DISCLAIMER
        yield {"citation_stripped": False}

    # ── seams ─────────────────────────────────────────────────────────────────

    async def _retrieve(self, session: Session, message: str) -> list:
        return await self._retrieve_skill.retrieve(
            query=message,
            candidate_id=session.candidate_id,
            school_id="",
            test_type=session.test_type,
            top_k=5,
        )

    def _check_citations(self, text: str, num_chunks: int) -> tuple[bool, list[str]]:
        return check_citations(text, num_chunks)

    async def _run_style_critic(self, essay_text: str) -> tuple[bool, str]:
        return await run_style_critic(essay_text, self._model_config_path)

    async def _get_personal_style_exemplars(self, session: Session) -> list[str]:
        if not session.personal_style_enabled:
            return []
        return await self._match_style_skill.get_exemplars(
            candidate_id=session.candidate_id,
            test_type=session.test_type,
        )

    async def _detect_task_type(self, message: str) -> str:
        if _ARGUMENT_KEYWORDS.search(message):
            return "argument"
        return "issue"
