export type Subject = "quant" | "aw";
export type Mode = "tutor" | "solve";
export type MessageRole = "candidate" | "agent";

export interface Citation {
  index: number;
  text: string;
  source_uri: string;
  page_or_section: string;
  tier: "global" | "school" | "candidate";
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  citations?: Citation[];
  status?: string; // "checking" | "retrieving" | null
  verifier_fail?: boolean;
  citation_stripped?: boolean;
}

export interface Session {
  id: string;
  subject: Subject;
  mode: Mode;
}

export const ESSAY_DISCLAIMER =
  "This sample essay was generated by an AI tutor for study purposes only. Do not submit it as your own work.";
